# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 569)
        font = QtGui.QFont()
        font.setFamily("Optima")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 60, 381, 371))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setStyleSheet("background-image: url(:/Users/elyneagapova/eclipse-workspace/Messenger/src/cat.png);")
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 440, 311, 51))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 450, 71, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.SayHello = QtWidgets.QLabel(self.centralwidget)
        self.SayHello.setGeometry(QtCore.QRect(70, 10, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(25)
        self.SayHello.setFont(font)
        self.SayHello.setText("")
        self.SayHello.setObjectName("SayHello")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setEnabled(True)
        self.logout.setGeometry(QtCore.QRect(20, 500, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        self.logout.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/hotpng.com-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout.setIcon(icon)
        self.logout.setIconSize(QtCore.QSize(30, 30))
        self.logout.setObjectName("logout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Meowssenger"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.logout.setText(_translate("MainWindow", "Logout"))
