# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(412, 612)
        font = QtGui.QFont()
        font.setFamily("Futura")
        StartWindow.setFont(font)
        StartWindow.setStyleSheet("background-image: url(:/Users/elyneagapova/eclipse-workspace/Messenger/src/cat.png);")
        StartWindow.setDocumentMode(False)
        StartWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.EditLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.EditLogin.setGeometry(QtCore.QRect(80, 170, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        self.EditLogin.setFont(font)
        self.EditLogin.setObjectName("EditLogin")
        self.EditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.EditPassword.setGeometry(QtCore.QRect(80, 220, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        self.EditPassword.setFont(font)
        self.EditPassword.setText("")
        self.EditPassword.setFrame(True)
        self.EditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.EditPassword.setDragEnabled(False)
        self.EditPassword.setReadOnly(False)
        self.EditPassword.setClearButtonEnabled(False)
        self.EditPassword.setObjectName("EditPassword")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 100, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(160, 280, 91, 41))
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.startButton.setTabletTracking(False)
        self.startButton.setAcceptDrops(False)
        self.startButton.setToolTipDuration(-1)
        self.startButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.startButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.startButton.setFlat(False)
        self.startButton.setObjectName("startButton")
        self.errorText = QtWidgets.QTextBrowser(self.centralwidget)
        self.errorText.setEnabled(False)
        self.errorText.setGeometry(QtCore.QRect(20, 320, 211, 21))
        self.errorText.setAcceptDrops(True)
        self.errorText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.errorText.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.errorText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.errorText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.errorText.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.errorText.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.errorText.setObjectName("errorText")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-230, 220, 711, 711))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../../Downloads/hotpng.com.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.EditLogin.raise_()
        self.EditPassword.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.startButton.raise_()
        self.errorText.raise_()
        StartWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "Meowsenger🐾"))
        self.EditLogin.setPlaceholderText(_translate("StartWindow", "Enter your nickname"))
        self.EditPassword.setPlaceholderText(_translate("StartWindow", "Enter your password"))
        self.label.setText(_translate("StartWindow", "Welcome to  🐾 "))
        self.label_2.setText(_translate("StartWindow", "Meowssenger"))
        self.startButton.setText(_translate("StartWindow", "Meow!"))
        self.errorText.setHtml(_translate("StartWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Futura\';\"><br /></p></body></html>"))
